apiVersion: v1
kind: SecretPolicy
secrets:
- spec:
    name: secret1-rsa-keypair
    # Default secret type is SECRET_TYPE_RSA_KEY_PAIR
    type: SECRET_TYPE_RSA_KEY_PAIR
    service: service1
    policy:
      enclaveMatchAnyRules:
      - mrenclave: ""
        # Default signing private key in Intel SDK sample code
        mrsigner: 83D719E77DEACA1470F6BAF62A4D774303C899DB69020F9C70EE1DFC08C7CE9E
        prodID: "0"
        minIsvSvn: "0"
        user_data: ""
        spid: ""
  data: ~
- spec:
    name: secret2-aes-key
    type: SECRET_TYPE_AES256_KEY
    service: service1
    policy:
      enclaveMatchAnyRules:
      - mrenclave: ""
        mrsigner: 83D719E77DEACA1470F6BAF62A4D774303C899DB69020F9C70EE1DFC08C7CE9E
        prodID: "0"
        minIsvSvn: "0"
        user_data: ""
        spid: ""
  data: ~
- spec:
    name: secret3-my-password
    type: SECRET_TYPE_IMPORT_DATA
    service: service1
    policy:
      enclaveMatchAnyRules:
      - mrenclave: ""
        mrsigner: 83D719E77DEACA1470F6BAF62A4D774303C899DB69020F9C70EE1DFC08C7CE9E
        prodID: "0"
        minIsvSvn: "0"
        user_data: ""
        spid: ""
  data: password-test
