apiVersion: v1
kind: SecretPolicy
secrets:
- spec:
    name: secret-my-password
    type: SECRET_TYPE_IMPORT_DATA
    service: service1
    readonly: "true"
    share: "public"
    policy:
      enclaveMatchAnyRules:
      - mrenclave: ""
        mrsigner: "" 
        prodID: ""
        minIsvSvn: "0"
        user_data: ""
        spid: ""
        debug_disabled: ""
  data: password-test
- spec:
    name: secret-my-aes256-key
    type: SECRET_TYPE_AES256_KEY
    service: service1
    readonly: "false"
    share: "private"
    policy:
      enclaveMatchAnyRules:
      - mrenclave: ""
        mrsigner: ""
        prodID: ""
        minIsvSvn: "0"
        user_data: ""
        spid: ""
        debug_disabled: ""
- spec:
    name: secret-my-keypair
    type: SECRET_TYPE_RSA_KEY_PAIR
    service: service1
    readonly: "true"
    share: "public"
    policy:
      enclaveMatchAnyRules:
      - mrenclave: ""
        mrsigner: ""
        prodID: ""
        minIsvSvn: "0"
        user_data: ""
        spid: ""
        debug_disabled: ""
    params:
    - key: "pkcs_type"
      value: "pkcs8"
    - key: "bit_length"
      value: 2048
- spec:
    name: secret-my-certificate
    type: SECRET_TYPE_CERTIFICATE
    service: service1
    readonly: "true"
    share: "public"
    policy:
      enclaveMatchAnyRules:
      - mrenclave: ""
        mrsigner: ""
        prodID: ""
        minIsvSvn: "0"
        user_data: ""
        spid: ""
        debug_disabled: ""
- spec:
    name: secret-my-sm2-keypair
    type: SECRET_TYPE_SM2_KEY_PAIR
    service: service1
    readonly: "true"
    share: "public"
    policy:
      enclaveMatchAnyRules:
      - mrenclave: ""
        mrsigner: ""
        prodID: ""
        minIsvSvn: "0"
        user_data: ""
        spid: ""
        debug_disabled: ""
- spec:
    name: secret-my-configuration
    type: SECRET_TYPE_CONFIGURATIONS
    service: service1
    readonly: "true"
    share: "public"
    policy:
      enclaveMatchAnyRules:
      - mrenclave: ""
        mrsigner: ""
        prodID: ""
        minIsvSvn: "0"
        user_data: ""
        spid: ""
        debug_disabled: ""
    params:
    - key: "id"
      value: "12345678"
    - key: "nonce"
      value: "1234567890abcdef"
