apiVersion: v1
kind: SecretPolicy
secrets:
- spec:
    name: secret-my-aes256-key
    type: SECRET_TYPE_AES256_KEY
    service:
    readonly: "false"
    share: "private"
    policy:
      enclaveMatchAnyRules:
      - mrenclave: ""
        mrsigner: ""
        prodID: ""
        minIsvSvn: ""
        user_data: ""
        spid: ""
        debug_disabled: ""